import datetime

import psycopg2

from RealTimeArrivals import Stop, Record
from Cruds import Crud


class CrudStub(Crud):
    def __init__(self):
        super().__init__()

    raw_stops = [{'route_id': 10802,
                  'route_long_name': 'כניסה ראשית/הדסה עין כרם-ירושלים<->האוניברסיטה העברית הר הצופים-ירושלים-1א',
                  'trip_id': '24104916_010117', 'stop_sequence': 1, 'stop_id': 9863, 'route_short_name': '19',
                  'shape_dist_traveled': 0, 'arrival_time': '18:15:00'}, {'route_id': 10802,
                                                                          'route_long_name': 'כניסה ראשית/הדסה עין '
                                                                                             'כרם-ירושלים<->האוניברסיטה העברית הר הצופים-ירושלים-1א',
                                                                          'trip_id': '24104916_010117',
                                                                          'stop_sequence': 2, 'stop_id': 9864,
                                                                          'route_short_name': '19',
                                                                          'shape_dist_traveled': 384,
                                                                          'arrival_time': '18:16:00'},
                 {'route_id': 10802,
                  'route_long_name': 'כניסה ראשית/הדסה עין כרם-ירושלים<->האוניברסיטה העברית הר הצופים-ירושלים-1א',
                  'trip_id': '24104916_010117', 'stop_sequence': 3, 'stop_id': 11227, 'route_short_name': '19',
                  'shape_dist_traveled': 2001, 'arrival_time': '18:21:00'}, {'route_id': 10802,
                                                                             'route_long_name': 'כניסה ראשית/הדסה עין כרם-ירושלים<->האוניברסיטה העברית הר הצופים-ירושלים-1א',
                                                                             'trip_id': '24104916_010117',
                                                                             'stop_sequence': 4, 'stop_id': 9334,
                                                                             'route_short_name': '19',
                                                                             'shape_dist_traveled': 2935,
                                                                             'arrival_time': '18:23:00'},
                 {'route_id': 10802,
                  'route_long_name': 'כניסה ראשית/הדסה עין כרם-ירושלים<->האוניברסיטה העברית הר הצופים-ירושלים-1א',
                  'trip_id': '24104916_010117', 'stop_sequence': 5, 'stop_id': 9301, 'route_short_name': '19',
                  'shape_dist_traveled': 3248, 'arrival_time': '18:24:00'}]

    raw_records = [{'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 35, 48,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.362768825871595},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 59, 42,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.724917949059644},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 33, 53,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.2968131348621},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 44, 5,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.535766213633687},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 22, 34,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.0},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 59, 42,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(
                                                              offset=0, name=None)),
                    'route_offset': 0.724917949059644},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 42, 5,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.491390258912908},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 57, 49,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.71496976404256},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 44, 5,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.535766213633687},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 59, 42,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.724917949059644},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 44, 5,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.535766213633687},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 30, 6,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.20809220334436},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 17, 8, 11,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.855217023041797},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 35, 48,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.362768825871595},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 30, 6,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.20809220334436},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 56, 3,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.683842018714419},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 22, 34,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.0},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 37, 55,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(
                                                              offset=0, name=None)),
                    'route_offset': 0.403927890512337},
                   {'vehicle_ref': '8761901', 'trip_id_from_gtfs': '24104916_010117',
                    'recorded_at_time': datetime.datetime(2017, 2, 2, 16, 39, 57,
                                                          tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=0,
                                                                                                 name=None)),
                    'route_offset': 0.416150359630258}]

    def read_stops(self, trip_id=None):
        return [Stop(**i) for i in CrudStub.raw_stops]

    def read_records_from_siri(self, trip_id=None, trip_date=None):
        return [Record(**i) for i in CrudStub.raw_records]